name: Cypress Tests

on:
  push:

jobs:
  cypress-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          wait-on: http://localhost:3000


      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            cypress/screenshots
            cypress/videos